backend:
  name: git-gateway
  branch: main
media_folder: "/assets/uploads"
show_preview_links: false
collections:
  - name: "settings"
    label: "Settings"
    editor: { preview: false }
    files:
      - file: "/src/data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "Ticker Text"
            name: "ticker_text"
            widget: "string"
  - name: "readings"
    label: "Readings"
    extension: "json"
    format: "json"
    label_singular: "Reading"
    editor: { preview: false }
    folder: "/src/data/readings"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: Text
        name: body
        widget: markdown
