backend:
  name: git-gateway
  branch: main
media_folder: "/public/uploads"
public_folder: "/uploads"
show_preview_links: false
site_url: https://love-actually.netlify.app/
collections:
  - name: "settings"
    label: "Settings"
    editor: { preview: false }
    files:
      - file: "/src/data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "Ticker Text"
            name: "ticker_text"
            widget: "string"
            hint: "Will be converted to all caps automatically."
          - label: "History"
            name: "history"
            widget: "markdown"
          - label: "Gallery Images"
            label_singular: "Gallery Image"
            collapsed: false
            name: "gallery"
            widget: "list"
            fields:
              - label: Image
                name: image
                widget: image
                media_library:
                  config:
                    max_file_size: 2000000
              - label: Description
                name: alt
                widget: string
                hint: "You should add a description to your images items so they’re accessible to more people, including those who are blind or visually impaired. Good descriptions are concise, but present what’s in your images accurately enough to understand their context."
  - name: "readings"
    label: "Readings"
    extension: "json"
    format: "json"
    label_singular: "Reading"
    editor: { preview: false }
    folder: "/src/data/readings"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: Text
        name: body
        widget: markdown
